[package]
name = "trdelniki"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
iced = { version = "0.13.1", features = ["image", "advanced"] }
image = "0.25.5"
imageproc = "0.25.0"
nalgebra = "0.33.2"
rfd = "0.15.3"
